### ISSUE TITLE
Program bug?

### ISSUE THREAD

**Issue by baronshark** [dslackw/slpkg#100]
Hello Dimitris, just to report the following finding:
The program breaks when you have a slackbuild in  /var/log/packages, in this case for some reason I had the file ninja-1.8.2-i586-1_SBo.tgz in that folder, and the following happened:

root_Juan@wifislax~ # slpkg health
.
.
.
usr/share/emacs/site-lisp/ninja-mode.el
usr/share/zsh/site-functions/_ninja
usr/share/bash-completion/completions/ninja
Not installed: /����㟃�\e� 
                           �P��P�Em���V�=X:ѧ;dK�(�i���PL� �J4����6K�f9���bl���Q�5�sp�&��ͨ�w=�Q���H�jnOLՖ --> ninja-1.8.2-i586-1_SBo.tgz
Traceback (most recent call last):
  File "/usr/bin/slpkg", line 41, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/slpkg/main.py", line 814, in main
    arguments[args[0]]()
  File "/usr/lib/python2.7/site-packages/slpkg/main.py", line 206, in command_health
    PackageHealth(mode="").test()
  File "/usr/lib/python2.7/site-packages/slpkg/health.py", line 81, in test
    self.check(line, pkg)
  File "/usr/lib/python2.7/site-packages/slpkg/health.py", line 57, in check
    if not os.path.isfile("/" + line):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: must be encoded string without NULL bytes, not str

The issue was fixed after removing the .tgz file from the folder, but I dont know if the program should behave like that...
Regards,

**Comment by dslackw** [comment]
Thanks for reporting!!

**Comment by baronshark** [comment]
You're welcome Dimitris :jack_o_lantern:
