### ISSUE TITLE
slpkg-3.8.5 build error

### ISSUE THREAD

**Issue by djringjr** [dslackw/slpkg#111]
```
``slpkg-3.8.5/tools/gen_repos_files.sh
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    from slpkg.__metadata__ import MetaData as _meta_
  File "/tmp/SBo/slpkg-3.8.5/slpkg/__metadata__.py", line 41
    repo_file = f"{conf_path}custom-repositories"
                                                ^
SyntaxError: invalid syntax
```

**Comment by dslackw** [comment]
Hi @djringjr,

Please use python3 instead of python2 and use [Gitlab repository](https://gitlab.com/dslackw/slpkg)

Best regards,
Dimitris

**Comment by djringjr** [comment]
I was installing with sbopkg.

Is there a way to get sbopkg to install it correctly?

Thanks,

David

**Comment by dslackw** [comment]
Hi @djringjr,

Yes, but before install slpkg you need to install python3 and urllib3 packages.
