### ISSUE TITLE
Find package error

### ISSUE THREAD

**Issue by lucashpandolfo** [dslackw/slpkg#13]
```bash
root@lambda:~# slpkg -f  whatever

Packages with matching name [ whatever ]

Traceback (most recent call last):
  File "/usr/bin/slpkg", line 40, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 397, in main
    arguments[args[0]]()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 304, in bin_find
    PackageManager(self.packages).find()
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 224, in find
    for match in find_package('', _m.pkg_path):
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/find.py", line 38, in find_package
    and split_package(pkg)[0] not in blacklist):
  File "/usr/lib64/python2.7/site-packages/slpkg/splitting.py", line 38, in split_package
    ver = split[-3]
IndexError: list index out of range
```

Runing the latest version.
I found where the problem is.

I have a package installed in my system with a 'bad' name: `dtn2-svn20110830`, and the name splitter asumes the format `name-version-arch-build`.

Removing the package from the system (or adding a dot to the corresponding file in /var/log/packages) solves the problem.

Can be either considered as a bug in slpkg or a bug in my system. Just reporting in case someone else has this problem.

Thanks for your hard work.

**Comment by dslackw** [comment]
Thank you very much for reporting,
We will fix this problem as soon as !
