### ISSUE TITLE
slpkg on Slackware64 13.37

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#28]
Hello @dslackw, I'm having some problems with running slpkg on 13.37...

A fresh Slackware64 13.37 installation:

1. Removed Python (2.6) `removepkg python`
2. Downloaded the slackbuild for Python 2.7.3 (from Slackware64 14.0) for  http://slackbuilds.org/mirror/slackware/slackware64-14.0/source/d/python/
3. Built and installed Python 2.7.3
4. Built and installed slpkg 2.6.0
5. Running slpkg:

~~~~
# slpkg update

Check and update repositories:

Update repository slack...  
Can't read file 'PACKAGES.TXT'

Can't read file 'PACKAGES.TXT'

Can't read file 'PACKAGES.TXT'
-
Can't read file 'CHECKSUMS.md5'

Can't read file 'CHECKSUMS.md5'

Can't read file 'CHECKSUMS.md5'
-
Can't read file 'PACKAGES.TXT'

Can't read file 'PACKAGES.TXT'

Can't read file 'PACKAGES.TXT'

Can't read file 'ChangeLog.txt'
-
Can't read file 'CHECKSUMS.md5'
Done
Update repository sbo...  
Can't read file 'SLACKBUILDS.TXT'
-
Can't read file 'SLACKBUILDS.TXT'

Can't read file 'ChangeLog.txt'
Done

~~~~

~~~~
# tree /var/lib/slpkg/
/var/lib/slpkg/
|-- sbo_repo
|   `-- SLACKBUILDS.TXT
`-- slack_repo
    |-- CHECKSUMS.md5
    `-- PACKAGES.TXT

2 directories, 3 files
~~~~

**Comment by dslackw** [comment]
Thank you. The process of updating the list of packages will be changed in a while. The existing process reads the file from the server and writes locally on the hard drive, but since the file behavior sometimes differs are created wrong, so think to change the process and to spend the downloaded (wget, aria2 etc).

**Comment by dslackw** [comment]
Please try out v2.6.1 and let me know if worked well.
Thank you again.

**Comment by websafe** [comment]
Thank you @dslackw , I've checked, it's still not working, but now we can see  what is wrong:

~~~~
# slpkg update

Check and update repositories:

Check repository [slack] ... 
[1/1][ Download ] --> PACKAGES.TXT

--2015-07-15 08:19:41--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:41 ERROR 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> PACKAGES.TXT

--2015-07-15 08:19:42--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/extra/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:43 ERROR 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> PACKAGES.TXT

--2015-07-15 08:19:43--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/pasture/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:44 ERROR 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2015-07-15 08:19:44--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:44 ERROR 404: Not Found.


+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2015-07-15 08:19:45--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/extra/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:45 ERROR 404: Not Found.


+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2015-07-15 08:19:46--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/pasture/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:48 ERROR 404: Not Found.


+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> ChangeLog.txt

--2015-07-15 08:19:49--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/ChangeLog.txt
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:50 ERROR 404: Not Found.


+==============================================================================
| Download 'ChangeLog.txt' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> PACKAGES.TXT

--2015-07-15 08:19:50--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:51 ERROR 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2015-07-15 08:19:52--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:52 ERROR 404: Not Found.


+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> PACKAGES.TXT

--2015-07-15 08:19:53--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/extra/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:53 ERROR 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> PACKAGES.TXT

--2015-07-15 08:19:54--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/pasture/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:55 ERROR 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2015-07-15 08:19:55--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/extra/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:56 ERROR 404: Not Found.


+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2015-07-15 08:19:56--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/pasture/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:57 ERROR 404: Not Found.


+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> ChangeLog.txt

--2015-07-15 08:19:57--  http://mirrors.slackware.com/slackware/slackware64-13.37.0/ChangeLog.txt
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-15 08:19:58 ERROR 404: Not Found.


+==============================================================================
| Download 'ChangeLog.txt' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y
Traceback (most recent call last):
  File "/usr/bin/slpkg", line 38, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 558, in main
    arguments[args[0]]()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 94, in command_update
    Update().repository(only="")
  File "/usr/lib64/python2.7/site-packages/slpkg/init.py", line 706, in repository
    exec("{0}.{1}()".format(self._init, repo))
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/slpkg/init.py", line 131, in slack
    "pasture/PACKAGES.TXT"])
  File "/usr/lib64/python2.7/site-packages/slpkg/init.py", line 632, in merge
    with open(path + i, "r") as in_f:
IOError: [Errno 2] No such file or directory: '/var/lib/slpkg/slack_repo/core/PACKAGES.TXT'
~~~~

The problem is caused by the URL, this one is wrong:

~~~~
http://mirrors.slackware.com/slackware/slackware64-13.37.0/
~~~~

should be:

~~~~
http://mirrors.slackware.com/slackware/slackware64-13.37/
~~~~

**Comment by dslackw** [comment]
Please print Slackware version file:
```
cat /etc/slackware-version
```

**Comment by websafe** [comment]
~~~~
# cat /etc/slackware-version 
Slackware 13.37.0
~~~~

http://mirrors.slackware.com/slackware/slackware64-13.37/source/a/aaa_base/slackware-version

**Comment by dslackw** [comment]
Can you check version 2.6.2 ?

**Comment by websafe** [comment]
Thank You @dslackw 2.6.2 works on 13.37 :-)
