### ISSUE TITLE
Installs fail with fresh install of Slpkg 2.6.1

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#30]
With slpkg, packages fail to auto install after building:

Traceback (most recent call last):
  File "/usr/bin/slpkg", line 38, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 558, in main
    arguments[args[0]]()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 262, in pkg_install
    SBoInstall(self.args[2:], flag).start(if_upgrade=False)
  File "/usr/lib64/python2.7/site-packages/slpkg/sbo/slackbuild.py", line 128, in start
    self._continue_to_install()
  File "/usr/lib64/python2.7/site-packages/slpkg/sbo/slackbuild.py", line 139, in _continue_to_install
    installs, upgraded = self.build_install()
  File "/usr/lib64/python2.7/site-packages/slpkg/sbo/slackbuild.py", line 315, in build_install
    if inst_pkg == pkg:
UnboundLocalError: local variable 'inst_pkg' referenced before assignment

This happens on both of my Slackware 14.1 machines.

**Comment by dslackw** [comment]
Thank you. Fixed in develop branch.

**Comment by Xylemon** [comment]
Thanks, fixed for me.
