### ISSUE TITLE
Cannot remove ftberm on -current

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#52]
##### Summary
Attempting to remove "fbterm" from my Slackware64-current "almost beta" system, I am unable to complete the task.  See output 1

EDIT:  Running slpkg 3.0.1.

To be sure it wasn't just fbterm, I tired it with another package.  See Output 2

##### Output 1

```bash
# slpkg -r fbterm

Packages with name matching [ fbterm ]

[ delete ] --> fbterm-1.7-x86_64-1_SBo
Traceback (most recent call last):
  File "/usr/bin/slpkg", line 41, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 759, in main
    arguments[args[0]]()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 557, in bin_remove
    PackageManager(packages).remove(flag, extra)
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 94, in remove
    self.removed = self._view_removed()
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 196, in _view_removed
    self._sizes(pkg)
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 410, in _sizes
    self.size += float(line[26:-1]) * 1024
ValueError: could not convert string to float: 
root@mothership[/etc/slpkg]# ls /var/log/packages/ | grep fbterm
fbterm-1.7-x86_64-1_SBo
```

##### Output 2
```bash
root@mothership[/etc/slpkg]# slpkg -r nikto

Packages with name matching [ nikto ]

[ delete ] --> nikto-2.1.5-x86_64-1_SBo
Traceback (most recent call last):
  File "/usr/bin/slpkg", line 41, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 759, in main
    arguments[args[0]]()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 557, in bin_remove
    PackageManager(packages).remove(flag, extra)
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 94, in remove
    self.removed = self._view_removed()
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 196, in _view_removed
    self._sizes(pkg)
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/manager.py", line 410, in _sizes
    self.size += float(line[26:-1]) * 1024
ValueError: could not convert string to float: 
```

**Comment by dslackw** [comment]
Strange, work for me in Slackware x86_64 -stable and Slackware x86 -current.

**Comment by BrentonEarl** [comment]
Possibly my mistake.  Not sure if I installed these packages using slpkg or sbopkg.  It makes sense that they could be installed using sbopkg and thats why slpkg didn't know about them to remove them.  I removed nikto and fbterm using removepkg and reinstalled them with slpkg -s sbo nikto; slpkg -s sbo fbterm and everything is working as it should be.

**Comment by BrentonEarl** [comment]
Maybe it is possible to add some logic that checks if the package is in slpkg's database.  If it isn't there report a message that states the package was likely not installed using slpkg.

**Comment by dslackw** [comment]
Very nice, now understood will try to find a solution. Thanks.

**Comment by dslackw** [comment]
Just now I installed fbterm with sbopkg and remove with slpkg without any problems.

**Comment by dslackw** [comment]
Anyway I make some changes that will work best in this area.

**Comment by BrentonEarl** [comment]
Ok great.  I still am not really sure what caused it.  I did switch my sbopkg repo from SBo-git to SBo 14.1 since a beta release candidate of 14.2 seems to be close.  Maybe something was confused in my pkgtools database.  I will close this ticket for now and reopen if I run into the problem again.
