### ISSUE TITLE
I can't install from slack repository

### ISSUE THREAD

**Issue by inukaze** [dslackw/slpkg#78]
Hi there. 

when i try install some package from slack repository , never ask for confirmation or deny just do nothing :+1: 

```
$ slpkg -s slack pygobject
Reading package lists... Done
Resolving dependencies... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  pygobject-2.28.6        2.28.6             x86_64  2      slack         404 K

Installing summary
===============================================================================
Total 1 package.
0 package will be installed, 0 will be upgraded and 1 will be reinstalled.
Need to get 404 Kb of archives.
After this process, 3.41 Mb of additional disk space will be used.

```

**Comment by dslackw** [comment]
Yes, because pygobject it is already installed. Try with flag --reinstall

**Comment by inukaze** [comment]
Ok , thank you for the information .

```
 slpkg -s slack pygobject --reinstall
Reading package lists... Done
Resolving dependencies... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  pygobject-2.28.6        2.28.6             x86_64  2      slack         404 K

Installing summary
===============================================================================
Total 1 package.
0 package will be installed, 0 will be upgraded and 1 will be reinstalled.
Need to get 404 Kb of archives.
After this process, 3.41 Mb of additional disk space will be used.

Would you like to continue [y/N]? y
```

**Comment by inukaze** [comment]
I have two dunnos : 

1 ) 
```
[ root | 26-01-2017 | 11:53 pm ]
[inukaze]#$ slpkg -s sbo pygobject
Reading package lists... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  pygobject3-python3-3.18.2 3.18.2             x86_64         SBo

Installing summary
===============================================================================
Total 1 package.
0 package will be installed, 1 already installed and 0 package
will be upgraded.

[ root | 26-01-2017 | 11:53 pm ]
[inukaze]#$ slpkg -r pygobject3

Packages with name matching [ pygobject3 ]

No such package pygobject3: Can't remove

[ root | 26-01-2017 | 11:54 pm ]
[inukaze]#$ removepkg pygobject

No such package: /var/log/packages/pygobject. Can't remove.

[ root | 26-01-2017 | 11:54 pm ]
[inukaze]#$ removepkg pygobject3

No such package: /var/log/packages/pygobject3. Can't remove.
```

if the package are not installed, why says is installed, and i can't reinstall it :(


When i try to "upgrade" the "sbo" installed packages ever stucks on : 

```
slpkg -c sbo --upgrade

  GISCAN   Libosinfo-1.0.gir
```

The problem is the package or the package manager ???

**Comment by dslackw** [comment]
These are three different packages:
```
pygobject
pygobject3-python3
pygobject3
```
You try to install pygobject from sbo repository and slpkg matching name with pygobject3-python3 package and after you try to remove pygobject3 and pygobject.

**Comment by inukaze** [comment]
Thanks for you answers and patience :D , thanks to you i had solve a problem with "Deluge" :D 
For 3-4 Days i can't started it :D 

The problem : 
```
$ deluge-gtk 
Traceback (most recent call last):
  File "/usr/bin/deluge-gtk", line 9, in <module>
    load_entry_point('deluge==1.3.13', 'gui_scripts', 'deluge-gtk')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/deluge/ui/gtkui/__init__.py", line 1, in <module>
    from gtkui import start
  File "/usr/lib64/python2.7/site-packages/deluge/ui/gtkui/gtkui.py", line 37, in <module>
    import gobject
  File "/usr/lib64/python2.7/site-packages/gobject/__init__.py", line 26, in <module>
    from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
  File "/usr/lib64/python2.7/site-packages/glib/__init__.py", line 22, in <module>
    from glib._glib import *
ImportError: /usr/lib64/python2.7/site-packages/glib/_glib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```

My solution : 

```
su

slpkg -r pyxdg python-twisted python-chardet pyOpenSSL libtorrent-rasterbar Mako MarkupSafe GeoIP cryptography idna ipaddress enum34 six cffi pyasn1 pycparser zope.interface deluge vala libgee 

removepkg pyxdg python-twisted python-chardet pyOpenSSL libtorrent-rasterbar Mako MarkupSafe GeoIP cryptography idna ipaddress enum34 six cffi pyasn1 pycparser zope.interface deluge vala libgee 

slpkg repo-enable #Enable : sbo & slonly

slpkg repo-add slwr64 http://mirrors.slackware.com/slackware/slackware64-current/

slpkg update

slpkg -s slonly python-unicodecsv Unidecode libgee libgee1 vala

slpkg -s slwr64 python-2.7.13 python-pillow python-setuptools pygtk pygobject gobject-insrospection 

slpkg -s sbo deluge

```
Now is fixed :D 

[![Deluge-fix.png](https://s25.postimg.org/62i8m2vn3/Deluge_fix.png)](https://postimg.org/image/7hjtaswq3/)

The problem looks like resides on "pygtk" after reinstall that package i need the "cryptography" package, is and dependecy autoresolve when i use slpkg to install deluge

**Comment by inukaze** [comment]
Hi there again, right now "slack" repository is working, but i just have a dunno, what is the url of that repository because inside the files on /etc/slpkg like 

default-repositories
repositories.conf

i dont find the url, is just for check its the not same url from my manually add of "slwr64"

**Comment by dslackw** [comment]
I don't know but dunno it is not default repositories for slpkg.
